### ISSUE TITLE
2020.02.1 tarball

### ISSUE THREAD

**Issue by Altai-man** [JJ/raku-alpine-test#1]
[MoarVM-2020.02.1.tar.gz](https://github.com/JJ/raku-alpine-test/files/4270965/MoarVM-2020.02.1.tar.gz)
For testing purposes.

**Comment by JJ** [comment]
OK, will check.

**Comment by JJ** [comment]
Far as I can tell, [it worked](https://hub.docker.com/r/jjmerelo/raku-alpine-provisional)
